version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/circleci-machiaruki-stamp-app
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run tests
          command: |
            pipenv run test
